### ISSUE TITLE
When testing encountered a problem in the production config file

### ISSUE THREAD

**Issue by rstento** [lagom/lagom-samples#42]
To get the Akka Cluster running, I had to change this line in prod-conf: coordinated-shutdown.exit-jvm = on to the value of off.

**Comment by ignasi35** [comment]
@rstento can you describe a bit more what tests where you performing? What was your target (minishift, minikube, centralpark2,...)?

What was the behavior you were observing and how did the change on the `coordinated-shutdown.exit-jvm` setting help?


Testing the correctness of shutdown is a very expensive process since there are multiple combinations and the setup and proper execution of each test are costly. Your details will greatly help track down potential bigs that may have slipped our tests. Thanks!

**Comment by TimMoore** [comment]
@rstento are you testing with the latest version of the code?

A previous version of the examples was explicitly setting this `on`, but that was later fixed: 

https://github.com/lagom/shopping-cart-scala/commit/a16c1b886df98ea7f096ba020e2d8b8276d6cacf

https://github.com/lagom/shopping-cart-java/commit/12e56f45e9fdfeaef5ba7a5fa9890ae879a0c0f2

The code in this repo doesn't include that setting, and relies on the (AFAIK correct) default behavior of Play & Lagom.

https://github.com/lagom/lagom-samples/blob/1.5.x/shopping-cart/shopping-cart-scala/shopping-cart/src/main/resources/prod-application.conf
https://github.com/lagom/lagom-samples/blob/1.5.x/shopping-cart/shopping-cart-java/shopping-cart/src/main/resources/prod-application.conf

**Comment by rstento** [comment]
@TimMoore @ignasi35, I had cloned the example when it was in the other repository, so most certainly didn't have the latest. It sounds like it's been fixed if it is set to off now. But just for the record, I was on Central Park and each of the clones would start, fail to find a cluster, restart, fail to find a cluster, and none of them would create the cluster first.

**Comment by TimMoore** [comment]
@rstento it doesn't seem to me like this setting should cause that problem, but I might be missing something. The setting that would cause that problem is `akka.management.cluster.bootstrap.new-cluster-enabled=off` or `akka.management.cluster.bootstrap.form-new-cluster=off`, which is an earlier name for the same setting that is still supported for backward compatibility. Is it possible that one of those was set?

Would you like to run through it again with the latest code as a double check or should we go ahead and close?

**Comment by rstento** [comment]
@TimMoore, actually, in the log there was a message suggesting I turn off a jvm setting, not the exact name of the one I turned off. Ed Callahan helped me find this one because apparently the name had changed. But, I will close this issue anyway since the default value has changed.
